# General  
finetune: True
partial_train: null

# Traning 
n_views: 2
temp: 0.1

epochs: 50
batch_size: 32 
lr_backbone: 0.0001
lr_head: 0.001
weight_decay: 0.01
lr_decay: 0.99

# Model
model_version: embed
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True
num_joints: 17
hidden_dim: 2048
dropout_ratio: 0.1

# Data
clip_len: 100

# Augmentation
random_move: True
scale_range_train: [1, 3]
scale_range_test: [2, 2]