# General  
finetune: True
partial_train: null
train_pw3d: True
warmup_h36m: 20
warmup_coco: 100

# Traning 
epochs: 60
checkpoint_frequency: 20
batch_size: 128
batch_size_img: 512
dropout: 0.1
lr_backbone: 0.00005
lr_head: 0.0005
weight_decay: 0.01
lr_decay: 0.98

# Model
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True
hidden_dim: 1024

# Data
data_root: data/mesh
dt_file_h36m: mesh_det_h36m.pkl
dt_file_coco: mesh_det_coco.pkl
dt_file_pw3d: mesh_det_pw3d.pkl
clip_len: 16
data_stride: 8
sample_stride: 1
num_joints: 17

# Loss
lambda_3d: 0.5
lambda_scale: 0
lambda_3dv: 10
lambda_lv: 0
lambda_lg: 0
lambda_a: 0
lambda_av: 0
lambda_pose: 1000
lambda_shape: 1
lambda_norm: 20
loss_type: 'L1'

# Augmentation
flip: True